### ISSUE TITLE
Add the option to open a text file or source code file in this app

### ISSUE THREAD

**Issue by Py-Marco** [massivemadness/Brackeys-IDE#61]
Hi, I have a **suggestion** for your code editor app from the **Google Play Store** and **F-Droid** app- Please add **the ability to open a text file or source code file in *this app** when the user is selecting an app to open a text file or source code file.*

And make it so that *this app* can be used to open ***any source code file*** in **any computer programming language**, like **PY files** (*files with ‘.py’ filename suffixes*) **for Python**, **JS files** *for JavaScript* and so on.

I would rate your app 5 stars on the Google Play Store when my suggestion is *implemented*. I also suggest adding **the ability to edit text files and source code files saved in a cloud storage like Google Drive**

**Comment by cewbdex** [comment]
I think it would be nice to write down the file extensions the app should be offered to open in. Or do you plan to offer for all file extensions? At the moment I would like to see support for log file, as I'm not a real fan of developing on phone, but when someone sends me a `*.log` file via email or telegram, I would like to be able to open in s decent app without saving it and then opening it. While it would be nice for source files too, I prefer opening the project folder, rather than only one file.

**Comment by mhdzumair** [comment]
I really want this feature. Mostly i work in termux folder. with barckeys ide i cannot open those folder. But in code edtior i can open by the option presenting as Open (SAF) then open the file with using MIX file manager. And also i can't open external sdcard files as well. Thanks in advanced.

**Comment by massivemadness** [comment]
@cewbdex I've added the `*.log` files support in commit f4fb1325d6f42d59683367e4ba9c2d2f18acaa99

**Comment by massivemadness** [comment]
@Py-Marco, @mhdzumair f3f9b7cfd17900ddbc96e621f50cb3afc924f5f4
